### ISSUE TITLE
captureMessage函数的第二个参数只能是级别

### ISSUE THREAD

**Issue by yinshipeng** [uappkit/sentry-uniapp#10]
`Sentry.captureMessage(
    'custom message from ' + uni.getSystemInfoSync().platform,
    {
      UserId: 123,
      Command: 'npm i -g uapp'
    }
  )`
第二个参数无效，只能设置info/warning这种消息级别

**Comment by zencodex** [comment]
没看明白你的问题，第二个参数是服务器收不到吗？

sentry 服务器 看 ADDITIONAL DATA 部分，就是第二个参数额外自定义部分数据。
