### ISSUE TITLE
pnpm 安装 sentry-uniapp报错

### ISSUE THREAD

**Issue by xmszm** [uappkit/sentry-uniapp#13]
pnpm 安装sentry-uniapp 在uniapp 编译会报没有安装依赖 如何兼容pnpm方式来做 不用拍平依赖的方法

**Comment by zencodex** [comment]
可以自己放到 uni_modules 里，注意引用路径

找不到，应该工程目录结构有问题，你可以用代码里的 uapp-demo 对比下

**Comment by limuen** [comment]
> 可以自己放到 uni_modules 里，注意引用路径
> 
> 找不到，应该工程目录结构有问题，你可以用代码里的 uapp-demo 对比下

目前我也遇到了，报sentry/type，sentry/core，sentry/utils错误。

让放到uni_module里面? 我们工程目录里面都没有找到这个文件 emmmm

**Comment by zencodex** [comment]
<img width="264" alt="image" src="https://github.com/user-attachments/assets/73134060-bd37-4c3e-ae94-ec9378bc6154">

安装完 node_modules 里是这样一个结构， `sentry/type，sentry/core，sentry/utils` 都在里，可以核对下

**Comment by limuen** [comment]
> <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/295317/367500076-73134060-bd37-4c3e-ae94-ec9378bc6154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjEwNzQsIm5iZiI6MTcyNjYyMDc3NCwicGF0aCI6Ii8yOTUzMTcvMzY3NTAwMDc2LTczMTM0MDYwLWJkMzctNGMzZS1hZTk0LWVjOTM3OGJjNjE1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMDUyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmEzY2EzMTY3Njk1Y2EwYzcyNjkxZmRmMDBhN2IxNjQzZWY4MWE3ODEwNzJhOTA1YzVkYzMxMzk2MDZmZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u4U_hJ-uvtmM940sWC022YeDSMSFEF8ZB6y9ZSgGEJ8">
> 安装完 node_modules 里是这样一个结构， `sentry/type，sentry/core，sentry/utils` 都在里，可以核对下

哈喽，刚测试了一下uapp-demo，pnpm安装不行，只能npm安装，但是新工程目录使用的pnpm emmmm

**Comment by limuen** [comment]
忘了回复了，上午留言完经过佬wx上的指导，已成功对接 🌹

**Comment by edk24** [comment]
> 忘了回复了，上午留言完经过佬wx上的指导，已成功对接 🌹

怎么解决的?  给个指导, 我也是用pnpm报了这个问题

**Comment by edk24** [comment]
我先用 npm 用上了

以下是我的依赖

```
"sentry-uniapp": "^1.0.12"
"@sentry/core": "^8.38.0",
"@sentry/utils": "^8.38.0",
"tslib": "^2.8.1",

// 开发依赖 (ts)
"@sentry/types": "^8.38.0"
```
