### ISSUE TITLE
sentry-quickapp get system info fail: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by huoxinqun** [uappkit/sentry-uniapp#3]
安卓12运行,发现报错
![image](https://user-images.githubusercontent.com/50652203/204445694-28cd8f79-8fcf-4561-8174-3f4f8624f1b1.png)
"sentry-uniapp": "^1.0.7",
![image](https://user-images.githubusercontent.com/50652203/204445773-f75378d9-5d5e-4b19-953f-bf1a73ff5b5b.png)

**Comment by zencodex** [comment]
log 提示是 sentry-quickapp? 你是用在快应用里吗？
需要确认下环境，只有快应用使用 `sentry-quickapp`，其余环境用 `sentry-uniapp`

**Comment by huoxinqun** [comment]
安卓

**Comment by huoxinqun** [comment]
我用 Hbuilder X 自定义打包一个 Uniapp 项目, 按照说明文档接入了此插件 `uappkit/sentry-uniapp`
当在安卓 12 的手机上运行时, 出现了上述的错误, 提示 "sentry-quickapp get system info fail: TypeError: Cannot read property 'split' of undefined", 并且手机白屏, 应用无法继续使用
请问如何解决,感谢大佬

**Comment by zencodex** [comment]
你的log 是提示的 sentry-quickapp，这个只能是快应用里使用。

白屏和获取信息失败问题，先去掉这个模块，保证工程正常编译并使用。之后再安装 sentry-uniapp，你的问题和sentry-uniapp 没关系。

**Comment by zencodex** [comment]
你是编译的什么平台，android，iOS，微信小程序，快应用？

**Comment by huoxinqun** [comment]
![image](https://user-images.githubusercontent.com/50652203/204549886-4a7e2918-19cb-4444-a6e3-0aa2a43a3e6f.png)
编译平台是 android;
无错误的时候,不会出现这个提示(不知道为什么会出现     sentry-quickapp get system info fail: TypeError: Cannot read property 'split' of undefined at node_modules/sentry-uniapp/esm/integrations/system.js:53    )

**Comment by zencodex** [comment]
fixed, 可以再看看
