### ISSUE TITLE
你好，为什么用uni-app 创建了一个App 项目，然后使用了 sentry-uniapp ，然后手机上运行会报错

### ISSUE THREAD

**Issue by ghost** [uappkit/sentry-uniapp#5]
代码如下：

<img width="1484" alt="wecom-temp-8f5b6358afde3e2f5c58ae7e9f2fe190" src="https://github.com/uappkit/sentry-uniapp/assets/40813278/8039c20e-3d98-4c2f-af71-45c353f53266">
`import * as Sentry from "sentry-uniapp"
Sentry.init({
  dsn: "后台获取的dsn地址"
})`

**Comment by ghost** [comment]
本地引用是可以的，就是npm 包是不行的

**Comment by zencodex** [comment]
> 本地引用是可以的，就是npm 包是不行的

1、检查下你npm install 的位置，打包后，可以去 unpackage/dist 下面搜索下 sentry-uniapp，如果没搜到就是没打包进去。

2、之前有朋友反馈的，就是装了 sentry h5 等其他的版本，需要都移除掉 sentry 相关的包，只保留  sentry-uniapp 这一个就可以。

**Comment by ghost** [comment]
请问npm install 的位置应该是哪里呢，我这边就是在项目的根目录下去安装的

**Comment by zencodex** [comment]
> 请问npm install 的位置应该是哪里呢，我这边就是在项目的根目录下去安装的

是的，正常是项目根目录。不过hbx创建项目，和uniapp-cli的目录结构不同。要看下是哪种创建方式。另外也可以通过安装其他npm包对比下是不是安装的姿势不对

如果没有和 sentry-uniapp 相关问题，本ISSUE将关闭。
