### ISSUE TITLE
使用nginx转发sentry请求时, 如何知道转发到哪个地址

### ISSUE THREAD

**Issue by ilp64** [uappkit/sentry-uniapp#6]
感谢作者提供这样一个好用的库，现在使用过程中有点问题，请教一下🙏

因为要在微信小程序中使用，所以要用自己已添加到小程序request白名单的域名做转发。
我看了下小程序中实际发出去的请求url和传入的dsn并不是一致的，我看在源码里有对url做过处理
https://github.com/uappkit/sentry-uniapp/blob/8f92c3fab3f8151979109fec089734dc92710a33/src/transports/base.ts#L16

那我在nginx里面配转发的时候，该转发到哪个后端地址呢？

**Comment by zencodex** [comment]
假如你的 sentry DNS 是：

`dsn: "https://123456@sentry.example.com/3",`

sentry.example.com 这个应该就是发出去的域名，你需要加到微信白名单里的，你看下对不。其他参数都加密串和project id，和域名没关系。

**Comment by ilp64** [comment]
@zencodex 谢谢大佬，小程序那边直接调自建的sentry域名就好了，确实不用先调到nginx上再转发
