### ISSUE TITLE
uniapp h5使用uni build构建后uni.getSystemInfoSync()报错

### ISSUE THREAD

**Issue by ilp64** [uappkit/sentry-uniapp#7]
错误信息：
`sentry-uniapp get system info fail: TypeError: SI.getSystemInfoSync is not a function`

应该是这行代码报的错
https://github.com/uappkit/sentry-uniapp/blob/8f92c3fab3f8151979109fec089734dc92710a33/src/integrations/system.ts#L26

我发现uniapp h5使用`uni build --mode xxx`构建后，在运行时`uni`这个对象下面只有跟路由相关的几个方法
![image](https://github.com/uappkit/sentry-uniapp/assets/20376547/b17a473e-a0c0-402a-82ff-1db8abaeeca0)

但如果是`uni --mode xxx`这种本地开发运行的时候，`uni`对象下面的方法就是和文档上一样正常的
![image](https://github.com/uappkit/sentry-uniapp/assets/20376547/c8a538db-5765-4b21-a0c4-055e4dd8b3fe)

一些uni相关的库版本：
```
    "@dcloudio/uni-app": "3.0.0-3070320230222002",
    "@dcloudio/uni-app-plus": "3.0.0-3070320230222002",
    "@dcloudio/uni-components": "3.0.0-3070320230222002",
    "@dcloudio/uni-h5": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-alipay": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-baidu": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-lark": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-qq": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-toutiao": "3.0.0-3070320230222002",
    "@dcloudio/uni-mp-weixin": "3.0.0-3070320230222002",
    "@dcloudio/uni-quickapp-webview": "3.0.0-3070320230222002",
    "@dcloudio/uni-ui": "^1.4.26",
```

**Comment by zencodex** [comment]
怎么编译的h5呢，编译命令是哪个。不能直接 看uni.* ，在 app 里不会暴露出来。
我h5 编译出来的是带 uni.getSystemInfoSync 的。你可以在浏览器里的 console 下，直接uni.getSystemInfoSync() 看是否有输出。

**Comment by ilp64** [comment]
> 怎么编译的h5呢，编译命令是哪个。不能直接 看uni.* ，在 app 里不会暴露出来。 我h5 编译出来的是带 uni.getSystemInfoSync 的。你可以在浏览器里的 console 下，直接uni.getSystemInfoSync() 看是否有输出。

是通过`uni build --mode dev`编译的，然后到`dist/build/h5`下起个静态文件服务，到浏览器里面访问，我这边浏览器控制台`uni.getSystemInfoSync`是`undefined`

![image](https://github.com/uappkit/sentry-uniapp/assets/20376547/8964d8b4-3454-4111-bbc2-055e742ac596)

如果是`uni --mode dev`这种命令本地运行的话，uni对象上是有那些方法的

大佬你用的uniapp h5是哪个版本，我用你那个版本试试看

**Comment by zencodex** [comment]
uni 是什么工具，没用过。正常官方 hbx 创建，或者 cli 创建的，应该都行吧

**Comment by ilp64** [comment]
我到uni社区那边问问看

**Comment by zencodex** [comment]
你说的是 package.json  里的 npm 命令里的 uni 吗，这个是 vue3 vite 的编译方式吧，我看你版本是 202302 ，这个应该偏低。你可以直接用 hbx 编译看下。uni.getSystemInfoSync 这个是 uniapp 的 api，没理由没有。

另外如果是 h5 使用，sentry 官方支持。

**Comment by ilp64** [comment]
> 你说的是 package.json 里的 npm 命令里的 uni 吗，这个是 vue3 vite 的编译方式吧，我看你版本是 202302 ，这个应该偏低。你可以直接用 hbx 编译看下。uni.getSystemInfoSync 这个是 uniapp 的 api，没理由没有。
> 
> 另外如果是 h5 使用，sentry 官方支持。

是vue3 vite的编译方式，问题找到了，是摇树导致的，开启摇树就会导致uni对象上少很多方法。
https://uniapp.dcloud.net.cn/collocation/manifest.html#treeshaking
我也打算h5平台使用官方的javascript-vue包的，但是好像没有办法获取router对象

**Comment by zencodex** [comment]
> > 你说的是 package.json 里的 npm 命令里的 uni 吗，这个是 vue3 vite 的编译方式吧，我看你版本是 202302 ，这个应该偏低。你可以直接用 hbx 编译看下。uni.getSystemInfoSync 这个是 uniapp 的 api，没理由没有。
> > 另外如果是 h5 使用，sentry 官方支持。
> 
> 是vue3 vite的编译方式，问题找到了，是摇树导致的，开启摇树就会导致uni对象上少很多方法。 https://uniapp.dcloud.net.cn/collocation/manifest.html#treeshaking 我也打算h5平台使用官方的javascript-vue包的，但是好像没有办法获取router对象

好的，如果有问题也可以加我微信 `28451307`，沟通更快些
