### ISSUE TITLE
小程序用的sentry dsn地址用的是sentry的saas服务地址，所以请求不出去？

### ISSUE THREAD

**Issue by AutumnWhj** [uappkit/sentry-uniapp#8]
问题是，我用postman 发送这个请求是可以成功的，但是在微信开发者工具不行。本地不校验域名的配置也打开了，不知道什么原因，有懂的大佬吗？
1、dsn地址用的是sentry的saas服务地址，没办法配置request合法域名的对吧？
2、微信开发者工具sentry请求超时
<img width="879" alt="image" src="https://github.com/uappkit/sentry-uniapp/assets/39156049/1a6e6e98-b8c0-4fe4-94b1-848d928dbeab">

**Comment by zencodex** [comment]
sentry 官方的 dsn？好像国内是被block的，你换个自己部署的服务器看下
