### ISSUE TITLE
uniapp(vue3+vite) 引入 sentry-uniapp 报错，无法运行

### ISSUE THREAD

**Issue by LunaYJ** [uappkit/sentry-uniapp#9]
使用方式，完全按照文档，在app onLaunch中引用

控制台报错内容：
[vite]: Rollup failed to resolve import "@sentry/hub" from "/Users/lunayj/Project/W+Group/Wise+/Product/member-center&CRM/wise-2023-member-center-mp-frontend/node_modules/@sentry/core/esm/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by zencodex** [comment]
可以看下代码里的 uapp-demo 示例，如果没问题，按照示例写
除了 sentry-uniapp 外，不要引入任何其他 sentry包，否则存在冲突可能。
